/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;

/**
 *
 * @author Hama
 */
public class Accueiladmin extends javax.swing.JFrame {

    /**
     * Creates new form Accueiladmin
     */
    public Accueiladmin() {
        initComponents();
    }

       public String genCode(String email)
    {
        
        meyel.setText(email);
        return email;
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        gererStade = new javax.swing.JButton();
        Gerermatch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        meyel = new javax.swing.JLabel();
        Gererresultat = new javax.swing.JButton();
        Gererticket = new javax.swing.JButton();
        dcnx = new javax.swing.JButton();
        BgererPari = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Binvitearbitre = new javax.swing.JButton();
        BpariJouer = new javax.swing.JButton();
        BAffArb = new javax.swing.JButton();
        Barticle = new javax.swing.JButton();
        BgererImage = new javax.swing.JButton();
        BInviterArbitre = new javax.swing.JButton();
        BajoutResult = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bautorisation = new javax.swing.JButton();
        BjeuResultat = new javax.swing.JButton();
        BpubluerStatut = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gererStade.setText("Gerer stade");
        gererStade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererStadeActionPerformed(evt);
            }
        });

        Gerermatch.setText("Gerer match");
        Gerermatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerermatchActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome ");

        meyel.setText("jLabel2");

        Gererresultat.setText("Gerer resultat");
        Gererresultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GererresultatActionPerformed(evt);
            }
        });

        Gererticket.setText("Gerer ticket");
        Gererticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GererticketActionPerformed(evt);
            }
        });

        dcnx.setText("Se déconnecter");
        dcnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcnxActionPerformed(evt);
            }
        });

        BgererPari.setText("Gerer Pari");
        BgererPari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgererPariActionPerformed(evt);
            }
        });

        jButton2.setText("jouer Pari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Binvitearbitre.setText("Inviter arbitre session");
        Binvitearbitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinvitearbitreActionPerformed(evt);
            }
        });

        BpariJouer.setText("voir Pari joué");
        BpariJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpariJouerActionPerformed(evt);
            }
        });

        BAffArb.setText("Affecter arbitre a un match");
        BAffArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAffArbActionPerformed(evt);
            }
        });

        Barticle.setText("Gerer Article");
        Barticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarticleActionPerformed(evt);
            }
        });

        BgererImage.setText("Gerer image");
        BgererImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BgererImageActionPerformed(evt);
            }
        });

        BInviterArbitre.setText("Invite arbitre Session");
        BInviterArbitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInviterArbitreActionPerformed(evt);
            }
        });

        BajoutResult.setText("Ajouter Resultat pour match");
        BajoutResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajoutResultActionPerformed(evt);
            }
        });

        jButton3.setText("Voir article");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Bautorisation.setText("autorization");
        Bautorisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BautorisationActionPerformed(evt);
            }
        });

        BjeuResultat.setText("Resultat jeu");
        BjeuResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BjeuResultatActionPerformed(evt);
            }
        });

        BpubluerStatut.setText("Publier Statut");
        BpubluerStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpubluerStatutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BInviterArbitre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BjeuResultat)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BAffArb)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(Gerermatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Gererticket, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BgererPari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(57, 57, 57)
                                .addComponent(Bautorisation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Gererresultat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BpubluerStatut)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Binvitearbitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BpariJouer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Barticle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcnx)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BajoutResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(meyel)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BgererImage)
                            .addComponent(gererStade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(257, 257, 257)
                    .addComponent(jButton3)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(meyel)
                    .addComponent(BajoutResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dcnx)
                    .addComponent(Barticle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gererStade)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Bautorisation))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Gerermatch)
                                    .addComponent(BgererImage))
                                .addGap(18, 18, 18)
                                .addComponent(BInviterArbitre)))
                        .addGap(18, 18, 18)
                        .addComponent(BjeuResultat))
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Binvitearbitre)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gererresultat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BgererPari)
                    .addComponent(BpariJouer)
                    .addComponent(Gererticket))
                .addGap(41, 41, 41)
                .addComponent(BAffArb)
                .addGap(18, 18, 18)
                .addComponent(BpubluerStatut)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jButton3)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerermatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerermatchActionPerformed
        // TODO add your handling code here:
        ListmatchFrame l =new  ListmatchFrame();
           this.setVisible(false);

        l.setVisible(true);
        
        
   String mail= meyel.getText();
   l.recuperermailticket1(mail);

        
    }//GEN-LAST:event_GerermatchActionPerformed

    private void gererStadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gererStadeActionPerformed
        // TODO add your handling code here:
                gererStadeFrame2 l =new  gererStadeFrame2();
                   this.setVisible(false);

        l.setVisible(true);

    }//GEN-LAST:event_gererStadeActionPerformed

    private void GererresultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GererresultatActionPerformed
        // TODO add your handling code here:
        
  /* ResultFrame l =new  ResultFrame();
   this.setVisible(false);
   l.setVisible(true);
   String mail= meyel.getText();
   l.recuperermailticket1(mail);*/

        
    }//GEN-LAST:event_GererresultatActionPerformed

    private void GererticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GererticketActionPerformed
        // TODO add your handling code here:
   
   GererticketFrame l =new  GererticketFrame();    
   this.setVisible(false);
   l.setVisible(true);
   String mail= meyel.getText();
   l.recuperermailticket1(mail);
                
   
    }//GEN-LAST:event_GererticketActionPerformed

    private void dcnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcnxActionPerformed

   Connect l =new Connect();
   this.setVisible(false);
   l.setVisible(true);
    
    }//GEN-LAST:event_dcnxActionPerformed

    private void BgererPariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgererPariActionPerformed
        // TODO add your handling code here:
           gererPariFrame3 l =new  gererPariFrame3();
   this.setVisible(false);
   l.setVisible(true);

    }//GEN-LAST:event_BgererPariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 gererJeuFrame l =new  gererJeuFrame();
   this.setVisible(false);
   l.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BinvitearbitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinvitearbitreActionPerformed
        // TODO add your handling code here:
        InviteArbitreSessionFrame2 l =new  InviteArbitreSessionFrame2();
   this.setVisible(false);
   l.setVisible(true); 
    }//GEN-LAST:event_BinvitearbitreActionPerformed

    private void BpariJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpariJouerActionPerformed
        // TODO add your handling code here:
      /*   jeuResultatFrame l =new  jeuResultatFrame();
   this.setVisible(false);
   l.setVisible(true); */
    }//GEN-LAST:event_BpariJouerActionPerformed

    private void BAffArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAffArbActionPerformed
Affecterarbitre l =new  Affecterarbitre();
        this.setVisible(false);
        l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BAffArbActionPerformed

    private void BarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarticleActionPerformed
GererImg l =new  GererImg();
        this.setVisible(false);
        l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BarticleActionPerformed

    private void BgererImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BgererImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BgererImageActionPerformed

    private void BInviterArbitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInviterArbitreActionPerformed
       InviteArbitreSessionFrame l =new  InviteArbitreSessionFrame();
        this.setVisible(false);
        l.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_BInviterArbitreActionPerformed

    private void BajoutResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajoutResultActionPerformed
      ResultFrame l =new  ResultFrame();
        this.setVisible(false);
        l.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_BajoutResultActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VoirArticle l =new  VoirArticle();
        this.setVisible(false);
        l.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BautorisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BautorisationActionPerformed
        // TODO add your handling code here:
         autorization l =new  autorization();
        this.setVisible(false);
        l.setVisible(true); 
    }//GEN-LAST:event_BautorisationActionPerformed

    private void BjeuResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BjeuResultatActionPerformed
        // TODO add your handling code here:
          jeuResultatFrame l =new  jeuResultatFrame();
        this.setVisible(false);
        l.setVisible(true); 
    }//GEN-LAST:event_BjeuResultatActionPerformed

    private void BpubluerStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpubluerStatutActionPerformed
  
        // TODO add your handling code here:
    }//GEN-LAST:event_BpubluerStatutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueiladmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAffArb;
    private javax.swing.JButton BInviterArbitre;
    private javax.swing.JButton BajoutResult;
    private javax.swing.JButton Barticle;
    private javax.swing.JButton Bautorisation;
    private javax.swing.JButton BgererImage;
    private javax.swing.JButton BgererPari;
    private javax.swing.JButton Binvitearbitre;
    private javax.swing.JButton BjeuResultat;
    private javax.swing.JButton BpariJouer;
    private javax.swing.JButton BpubluerStatut;
    private javax.swing.JButton Gerermatch;
    private javax.swing.JButton Gererresultat;
    private javax.swing.JButton Gererticket;
    private javax.swing.JButton dcnx;
    private javax.swing.JButton gererStade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel meyel;
    // End of variables declaration//GEN-END:variables
}
