/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui; 
        
import com.esprit.TFTpro.gui.Accueiladmin;
import com.esprit.TFTpro.gui.Connect;
import com.esprit.TFTpro.gui.GererticketFrame;
import com.esprit.TFTpro.gui.ListmatchFrame;
import com.esprit.TFTpro.gui.ResultFrame;

/**
 *
 * @author Hama
 */
public class Accueiladminhama extends javax.swing.JFrame {

    /**
     * Creates new form Accueiladmin
     */
    public Accueiladminhama() {
        initComponents();
    }

       public String genCode(String email)
    {
        
        meyel.setText(email);
        return email;
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gererStade = new javax.swing.JButton();
        Gerermatch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        meyel = new javax.swing.JLabel();
        Gererresultat = new javax.swing.JButton();
        Gererticket = new javax.swing.JButton();
        dcnx = new javax.swing.JButton();
        Gerersession = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gererStade.setText("Gerer stade");
        gererStade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererStadeActionPerformed(evt);
            }
        });

        Gerermatch.setText("Gerer match");
        Gerermatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerermatchActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome ");

        meyel.setText("jLabel2");

        Gererresultat.setText("Gerer resultat");
        Gererresultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GererresultatActionPerformed(evt);
            }
        });

        Gererticket.setText("Gerer ticket");
        Gererticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GererticketActionPerformed(evt);
            }
        });

        dcnx.setText("Se déconnecter");
        dcnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcnxActionPerformed(evt);
            }
        });

        Gerersession.setText("Gerer session");
        Gerersession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerersessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(meyel)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dcnx)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gererStade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gerermatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gererresultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gererticket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gerersession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(meyel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcnx)
                .addGap(9, 9, 9)
                .addComponent(gererStade)
                .addGap(18, 18, 18)
                .addComponent(Gerermatch)
                .addGap(18, 18, 18)
                .addComponent(Gererresultat)
                .addGap(18, 18, 18)
                .addComponent(Gererticket)
                .addGap(18, 18, 18)
                .addComponent(Gerersession)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerermatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerermatchActionPerformed
        // TODO add your handling code here:
        ListmatchFrame l =new  ListmatchFrame();
           this.setVisible(false);

        l.setVisible(true);
        
        
   String mail= meyel.getText();
   l.recuperermailticket1(mail);

        
    }//GEN-LAST:event_GerermatchActionPerformed

    private void gererStadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gererStadeActionPerformed
        // TODO add your handling code here:
               

    }//GEN-LAST:event_gererStadeActionPerformed

    private void GererresultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GererresultatActionPerformed
        // TODO add your handling code here:
        
   ResultFrame l =new  ResultFrame();
   this.setVisible(false);
   l.setVisible(true);
   String mail= meyel.getText();
   l.recuperermailticket1(mail);

        
    }//GEN-LAST:event_GererresultatActionPerformed

    private void GererticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GererticketActionPerformed
        // TODO add your handling code here:
   
   GererticketFrame l =new  GererticketFrame();    
   this.setVisible(false);
   l.setVisible(true);
   String mail= meyel.getText();
   l.recuperermailticket1(mail);
                
   
    }//GEN-LAST:event_GererticketActionPerformed

    private void dcnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcnxActionPerformed

   Connect l =new  Connect();
   this.setVisible(false);
   l.setVisible(true);
    
    }//GEN-LAST:event_dcnxActionPerformed

    private void GerersessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerersessionActionPerformed
        // TODO add your handling code here:


    
   
   
    }//GEN-LAST:event_GerersessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueiladmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gerermatch;
    private javax.swing.JButton Gererresultat;
    private javax.swing.JButton Gerersession;
    private javax.swing.JButton Gererticket;
    private javax.swing.JButton dcnx;
    private javax.swing.JButton gererStade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel meyel;
    // End of variables declaration//GEN-END:variables
}
