/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;

/**
 *
 * @author Mohamed
 */
public class Accueiluser extends javax.swing.JFrame {

    /**
     * Creates new form Accueiluser
     */
    public Accueiluser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendmail = new javax.swing.JButton();
        acheterticket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        meyel = new javax.swing.JLabel();
        dcnx = new javax.swing.JButton();
        BpariJouer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BconsulterClient = new javax.swing.JButton();
        BvoirImage = new javax.swing.JButton();
        BForum = new javax.swing.JButton();
        BacheterTicket = new javax.swing.JButton();
        BcontacteAdmin = new javax.swing.JButton();
        BvoirVideo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BjeuResultat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendmail.setText("Send mail");
        sendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmailActionPerformed(evt);
            }
        });

        acheterticket.setText("Acheter ticket");
        acheterticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acheterticketActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome ");

        meyel.setText("jLabel2");

        dcnx.setText("Se déconnecter");
        dcnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcnxActionPerformed(evt);
            }
        });

        BpariJouer.setText("voir Pari joué");
        BpariJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpariJouerActionPerformed(evt);
            }
        });

        jButton2.setText("jouer Pari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BconsulterClient.setText("consulter article");
        BconsulterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconsulterClientActionPerformed(evt);
            }
        });

        BvoirImage.setText("Voir Image");
        BvoirImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvoirImageActionPerformed(evt);
            }
        });

        BForum.setText("Forum");
        BForum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BForumActionPerformed(evt);
            }
        });

        BacheterTicket.setText("acheter Tickets");
        BacheterTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacheterTicketActionPerformed(evt);
            }
        });

        BcontacteAdmin.setText("Contacter Administrateur");
        BcontacteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcontacteAdminActionPerformed(evt);
            }
        });

        BvoirVideo.setText("Voir video");
        BvoirVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvoirVideoActionPerformed(evt);
            }
        });

        jButton1.setText("Voir article");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BjeuResultat.setText("Resultat jeu");
        BjeuResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BjeuResultatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(acheterticket))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BForum)
                                            .addComponent(BvoirImage))
                                        .addGap(154, 154, 154)
                                        .addComponent(BacheterTicket))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BvoirVideo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sendmail)
                                        .addGap(8, 8, 8))
                                    .addComponent(BconsulterClient))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(286, Short.MAX_VALUE)
                        .addComponent(BpariJouer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BcontacteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(meyel)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BjeuResultat)
                                .addComponent(dcnx)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(meyel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BcontacteAdmin)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcnx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(BjeuResultat)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(BconsulterClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BvoirImage)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BpariJouer)
                    .addComponent(acheterticket))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BForum)
                        .addGap(28, 28, 28)
                        .addComponent(BvoirVideo)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(BacheterTicket)
                        .addGap(18, 18, 18)
                        .addComponent(sendmail)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public String genCode(String email)
    {
        
        meyel.setText(email);
        return email;
        
        
    }
    private void sendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendmailActionPerformed

    private void dcnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcnxActionPerformed

        Connect l =new  Connect();
        this.setVisible(false);
        l.setVisible(true);

    }//GEN-LAST:event_dcnxActionPerformed

    private void acheterticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acheterticketActionPerformed
        // TODO add your handling code here:
                AcheterticketFrame l =new  AcheterticketFrame();
           this.setVisible(false);

        l.setVisible(true);
        
        
   String mail= meyel.getText();
   l.genCode(mail);

    }//GEN-LAST:event_acheterticketActionPerformed

    private void BpariJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpariJouerActionPerformed
        // TODO add your handling code here:
        /*   jeuResultatFrame l =new  jeuResultatFrame();
        this.setVisible(false);
        l.setVisible(true); */
    }//GEN-LAST:event_BpariJouerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gererJeuFrame l =new  gererJeuFrame();
        this.setVisible(false);
        l.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BconsulterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconsulterClientActionPerformed
AffArticleClient l =new  AffArticleClient();
        this.setVisible(false);
        l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BconsulterClientActionPerformed

    private void BvoirImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvoirImageActionPerformed
AffImageClient l =new  AffImageClient();
        this.setVisible(false);
        l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BvoirImageActionPerformed

    private void BForumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BForumActionPerformed
Forum l =new  Forum();
        this.setVisible(false);
        l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BForumActionPerformed

    private void BacheterTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacheterTicketActionPerformed
AcheterticketFrame l =new  AcheterticketFrame();
        this.setVisible(false);
        l.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BacheterTicketActionPerformed

    private void BcontacteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcontacteAdminActionPerformed
        MailJF l =new  MailJF();
        this.setVisible(false);
        l.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BcontacteAdminActionPerformed

    private void BvoirVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvoirVideoActionPerformed
        // TODO add your handling code here:
    
     
    }//GEN-LAST:event_BvoirVideoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
VoirArticle2 l =new  VoirArticle2();
        this.setVisible(false);
        l.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BjeuResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BjeuResultatActionPerformed
        // TODO add your handling code here:
        jeuResultatFrame l =new  jeuResultatFrame();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_BjeuResultatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueiluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueiluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueiluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueiluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueiluser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BForum;
    private javax.swing.JButton BacheterTicket;
    private javax.swing.JButton BconsulterClient;
    private javax.swing.JButton BcontacteAdmin;
    private javax.swing.JButton BjeuResultat;
    private javax.swing.JButton BpariJouer;
    private javax.swing.JButton BvoirImage;
    private javax.swing.JButton BvoirVideo;
    private javax.swing.JButton acheterticket;
    private javax.swing.JButton dcnx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel meyel;
    private javax.swing.JButton sendmail;
    // End of variables declaration//GEN-END:variables
}
