/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;

import com.esprit.TFTpro.adpaters.TicketAdapter;

import com.esprit.TFTpro.dao.classes.AcheterticketDAO;
import com.esprit.TFTpro.dao.classes.MatcheDAO; 
import com.esprit.TFTpro.dao.classes.TicketDAO;
import com.esprit.TFTpro.dao.classes.UtilisateurDAO;

import com.esprit.hellopi.dao.interfaces.IacheterticketDAO; 
import com.esprit.hellopi.dao.interfaces.ImatcheDAO;
import com.esprit.hellopi.dao.interfaces.IticketDAO;
import com.esprit.hellopi.dao.interfaces.IUtilisateurDAO; 
import com.esprit.TFTpro.entities.Matche;
import com.esprit.TFTpro.entities.Ticket;
import com.esprit.TFTpro.entities.Utilisateur;

import com.esprit.technique.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hama
 */
public class AcheterticketFrame extends javax.swing.JFrame {

    /**
     * Creates new form AcheterticketFrame
     */
    public AcheterticketFrame() {
        initComponents();
        
        
      
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
Connection connection;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Ajouter_panier = new javax.swing.JButton();
        Viderpanier = new javax.swing.JButton();
        Acheterticket = new javax.swing.JButton();
        list1 = new java.awt.List();
        list2 = new java.awt.List();
        jToggleButton3 = new javax.swing.JToggleButton();
        total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        list3 = new java.awt.List();
        meyel = new javax.swing.JLabel();
        solde_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        afficher_solde = new javax.swing.JButton();
        dcnx = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTable1.setModel(new TicketAdapter());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 14, 330, 266);

        Ajouter_panier.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Ajouter_panier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/ajouter-orange-plus-icone-4021-128.png"))); // NOI18N
        Ajouter_panier.setText("Ajouter au panier");
        Ajouter_panier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter_panierActionPerformed(evt);
            }
        });
        getContentPane().add(Ajouter_panier);
        Ajouter_panier.setBounds(10, 410, 230, 60);

        Viderpanier.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Viderpanier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/poubl.png"))); // NOI18N
        Viderpanier.setText("Vider le panier ");
        Viderpanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViderpanierActionPerformed(evt);
            }
        });
        getContentPane().add(Viderpanier);
        Viderpanier.setBounds(250, 410, 180, 60);

        Acheterticket.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Acheterticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/qchtr.png"))); // NOI18N
        Acheterticket.setText("Acheter");
        Acheterticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcheterticketActionPerformed(evt);
            }
        });
        getContentPane().add(Acheterticket);
        Acheterticket.setBounds(720, 410, 140, 60);

        list1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(list1);
        list1.setBounds(350, 10, 113, 265);

        list2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(list2);
        list2.setBounds(470, 10, 118, 265);

        jToggleButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/DAS.png"))); // NOI18N
        jToggleButton3.setText("Calculer le montant");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(450, 410, 230, 60);

        total.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(total);
        total.setBounds(600, 310, 120, 60);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Total :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 330, 60, 20);

        list3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(list3);
        list3.setBounds(600, 10, 118, 265);

        meyel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        getContentPane().add(meyel);
        meyel.setBounds(770, 120, 60, 40);

        solde_label.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(solde_label);
        solde_label.setBounds(770, 270, 90, 41);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel1.setText("Bienvenue");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 90, 100, 30);

        afficher_solde.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        afficher_solde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/DAS.png"))); // NOI18N
        afficher_solde.setText("Get Solde");
        afficher_solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher_soldeActionPerformed(evt);
            }
        });
        getContentPane().add(afficher_solde);
        afficher_solde.setBounds(720, 200, 150, 60);

        dcnx.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dcnx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/dc.png"))); // NOI18N
        dcnx.setText("Se déconnecter");
        dcnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcnxActionPerformed(evt);
            }
        });
        getContentPane().add(dcnx);
        dcnx.setBounds(720, 10, 150, 60);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/hellopi/gui/421343.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 880, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public String genCode(String email)
    {
        
        meyel.setText(email);
        return email;
        
        
    }
    private void Ajouter_panierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter_panierActionPerformed
        
        int selectedRow = jTable1.getSelectedRow();
        jTable1.getValueAt(selectedRow, 0);
        list1.add(jTable1.getValueAt(selectedRow, 1).toString());
        //  result.setSet1joueur1(Integer.parseInt(set1joueur1_ajoutresultat1.getSelectedItem().toString()));

        list2.add(jTable1.getValueAt(selectedRow, 2).toString());
        list3.add(jTable1.getValueAt(selectedRow, 3).toString());

        
// TODO add your handling code here:

    }//GEN-LAST:event_Ajouter_panierActionPerformed

    private void ViderpanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViderpanierActionPerformed
        // TODO add your handling code here:
        list1.removeAll();
        list2.removeAll();
        list3.removeAll();

    }//GEN-LAST:event_ViderpanierActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        float sum=0;
        for(int i=0;i<list2.getItemCount();i++){
            sum= sum +Float.parseFloat(list2.getItem(i));
        }

        total.setText(String.valueOf(sum));

        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void AcheterticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcheterticketActionPerformed
        // TODO add your handling code here:
        Integer sum=0;                                        
        connection=DataSource.getInstance().getConnection();
        DataSource.getInstance();
        IacheterticketDAO dao=new AcheterticketDAO();
        IticketDAO daoo=new TicketDAO();
        IUtilisateurDAO da=new UtilisateurDAO();
        Ticket ticket= new Ticket();
        Utilisateur utilisateur=new Utilisateur();
        
      
        
           for(int i=0;i<list2.getItemCount();i++)
           {
            sum= sum +Integer.parseInt(list2.getItem(i));
           }
         

utilisateur.setSolde(Integer.parseInt(solde_label.getText())-sum);
utilisateur.setEmail(meyel.getText());        
      
    
        
        
        
        
//actualisé labelle solde

try {         
                 String sql="select * from utilisateurs where email=?";
                 PreparedStatement pst = connection.prepareStatement(sql);
                 pst.setString(1,meyel.getText());        
                 ResultSet rs = pst.executeQuery();
                 
if(rs.next())
{
    
    String add1=rs.getString("solde");        
    solde_label.setText(add1);

}
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } 
        


       







        
        
        
  for(int i=0;i<list3.getItemCount();i++)
  {
      
              int a=(Integer.parseInt(list3.getItem(i)));

                  if(a<1){
                   JOptionPane.showMessageDialog(null,"les tickets du match qui se déroule entre "+list1.getItem(i)+ " ont été tous vendu ");

        } 
                  
          else {           
      
      String  joueurs=(list1.getItem(i));
      ticket.setNbtotal(a-1);
      ticket.setJoueurs(joueurs);
      
 
      
      dao.update(ticket);
   

      daoo.select();
      
      jTable1.setModel(new TicketAdapter());
        
        
  }
               
  }                            
  
   System.out.println(meyel.getText());
                
   
  
    
        
        
    }//GEN-LAST:event_AcheterticketActionPerformed

    
    private void afficher_soldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher_soldeActionPerformed
        // TODO add your handling code here:
       
          
      
          connection=DataSource.getInstance().getConnection();
        DataSource.getInstance();
        IacheterticketDAO dao=new AcheterticketDAO();
        IticketDAO daoo=new TicketDAO();
        IUtilisateurDAO da=new UtilisateurDAO();
        Ticket ticket= new Ticket();
     Utilisateur utilisateur=new Utilisateur();
        try {         
                 String sql="select * from utilisateurs where email=?";
                 PreparedStatement pst = connection.prepareStatement(sql);
                 pst.setString(1,meyel.getText());        
                 ResultSet rs = pst.executeQuery();
                 
if(rs.next())
{
    
    String add1=rs.getString("solde");        
    solde_label.setText(add1);

}
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        } 
        
        
        
        
    }//GEN-LAST:event_afficher_soldeActionPerformed

    private void dcnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcnxActionPerformed

        Connect l =new  Connect();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_dcnxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcheterticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcheterticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcheterticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcheterticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcheterticketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acheterticket;
    private javax.swing.JButton Ajouter_panier;
    private javax.swing.JButton Viderpanier;
    private javax.swing.JButton afficher_solde;
    private javax.swing.JLabel bg;
    private javax.swing.JButton dcnx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton3;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.List list3;
    private javax.swing.JLabel meyel;
    private javax.swing.JLabel solde_label;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
