/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;

import com.esprit.TFTpro.dao.classes.MatcheDAO;
import com.esprit.TFTpro.dao.classes.ResultDAO;
import com.esprit.TFTpro.dao.classes.TicketDAO;
import com.esprit.hellopi.dao.interfaces.ImatcheDAO;
import com.esprit.hellopi.dao.interfaces.IresultDAO;
import com.esprit.hellopi.dao.interfaces.IticketDAO;
import com.esprit.TFTpro.entities.Matche;
import com.esprit.TFTpro.entities.Result;
import com.esprit.TFTpro.entities.Ticket;
import com.esprit.technique.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.esprit.TFTpro.adpaters.TicketAdapter;
import com.esprit.TFTpro.adpaters.TicketAdapter2;
import javax.swing.JOptionPane;

/**
 *
 * @author Hama
 */
public class GererticketFrame extends javax.swing.JFrame {

    /**
     * Creates new form GererticketFrame
     */
    public GererticketFrame() {
        Connection connection;
        initComponents();
        connection= DataSource.getInstance().getConnection();
        
        
        DataSource.getInstance();
      ImatcheDAO dao=new MatcheDAO() {};
        Matche Matche= new Matche();
        
         connection= DataSource.getInstance().getConnection();
 
        DataSource.getInstance();
        
  
        
        
                 String sql="Select *  from matches "; 

              try {
 PreparedStatement ps=connection.prepareStatement(sql);
 ResultSet res = ps.executeQuery();

 
            while(res.next()  )
            {
 ticket_joueurs.addItem(res.getString("nomjoueur1") +"  "+res.getString("nomjoueur2") );
 


        }
              }
              catch (SQLException ex) {
            Logger.getLogger(MatcheDAO.class.getName()).log(Level.SEVERE, null, ex);
        }

            

        
        
              
              
              
              
              
              
              
    }
    
       public String recuperermailticket1(String email)
    {
        
        meyelmatch.setText(email);
        return email;
        
        
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ticket_joueurs = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ajouterticket = new javax.swing.JButton();
        prixticket = new javax.swing.JSpinner();
        nbr_ticket = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableafficherticket = new javax.swing.JTable();
        dcnx = new javax.swing.JButton();
        meyelmatch = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modifierticket = new javax.swing.JButton();
        supprimerticket = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idticket = new javax.swing.JLabel();
        rechercherticket = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Les Joueurs");

        jLabel2.setText("Nombre de tickets");

        jLabel3.setText("Prix");

        Ajouterticket.setText("Ajouter");
        Ajouterticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterticketActionPerformed(evt);
            }
        });

        tableafficherticket.setModel(new TicketAdapter());
        tableafficherticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableafficherticketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableafficherticket);

        dcnx.setText("Se déconnecter");
        dcnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcnxActionPerformed(evt);
            }
        });

        jLabel4.setText("Welcome ");

        modifierticket.setText("Modifier");
        modifierticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierticketActionPerformed(evt);
            }
        });

        supprimerticket.setText("Supprimer");
        supprimerticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerticketActionPerformed(evt);
            }
        });

        jLabel5.setText("Id");

        rechercherticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherticketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(dcnx))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(meyelmatch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(Ajouterticket)
                        .addGap(37, 37, 37)
                        .addComponent(modifierticket)
                        .addGap(36, 36, 36)
                        .addComponent(supprimerticket)
                        .addGap(31, 31, 31)
                        .addComponent(rechercherticket, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ticket_joueurs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nbr_ticket)
                                    .addComponent(prixticket, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idticket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(meyelmatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addComponent(dcnx))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(idticket, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ticket_joueurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nbr_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prixticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouterticket)
                    .addComponent(modifierticket)
                    .addComponent(supprimerticket)
                    .addComponent(rechercherticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterticketActionPerformed
        // TODO add your handling code here:
        DataSource.getInstance();
        IticketDAO dao=new TicketDAO();
        Ticket ticket= new Ticket();
       // result.setJoueur1(joueur1_ajoutresultat.getText());
       // result.setJoueur1(joueur2_ajoutresultat.getText());
  ticket.setJoueurs(ticket_joueurs.getSelectedItem().toString());
  ticket.setPrix((Integer) prixticket.getValue());
  ticket.setNbtotal((Integer) nbr_ticket.getValue());
         
        
        dao.add(ticket);
           dao.select();
  tableafficherticket.setModel(new TicketAdapter());

    }//GEN-LAST:event_AjouterticketActionPerformed

    private void dcnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcnxActionPerformed
        // TODO add your handling code here:
           Connect l =new  Connect();
   this.setVisible(false);
   l.setVisible(true);
    }//GEN-LAST:event_dcnxActionPerformed

    private void modifierticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierticketActionPerformed
        // TODO add your handling code here:
        
        
        
          DataSource.getInstance();
        TicketAdapter sa = new TicketAdapter();
        int x = tableafficherticket.getSelectedRow();
        IticketDAO dao=new TicketDAO();
        Ticket ticket= new Ticket();
        

        
        
        
  ticket.setIdticket(Integer.parseInt(idticket.getText()));
        System.out.println(idticket.getText());
  ticket.setJoueurs(ticket_joueurs.getSelectedItem().toString());
  ticket.setPrix((Integer) prixticket.getValue());
  ticket.setNbtotal((Integer) nbr_ticket.getValue());

        
dao.update(ticket);
        JOptionPane.showMessageDialog(null, "Votre stade a ete modifier", "", JOptionPane.WARNING_MESSAGE);

                tableafficherticket.setModel(new TicketAdapter());

   
    }//GEN-LAST:event_modifierticketActionPerformed

    private void tableafficherticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableafficherticketMouseClicked
        // TODO add your handling code here:
                TicketAdapter sa = new TicketAdapter();
        int x = tableafficherticket.getSelectedRow();

  String id = sa.getValueAt(x, 0).toString();
  
  idticket.setText(id);

    }//GEN-LAST:event_tableafficherticketMouseClicked

    private void rechercherticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherticketActionPerformed
        // TODO add your handling code here:
                IticketDAO dao = new TicketDAO();
        
        Ticket ticket = new Ticket();
        String s=rechercherticket.getText();

        
        tableafficherticket.setModel(new TicketAdapter2(s));

    }//GEN-LAST:event_rechercherticketActionPerformed

    private void supprimerticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerticketActionPerformed
        // TODO add your handling code here:
         IticketDAO dao = new TicketDAO();

               TicketAdapter ma = new TicketAdapter();
        int x = tableafficherticket.getSelectedRow();
        
        if(x == -1){
            
        JOptionPane.showMessageDialog(null, "\"Veuillez sélectioné une session !\"");
            
        }else{

            int Idticket = Integer.parseInt(ma.getValueAt(x, 0).toString());
         //   System.out.println(id);
            new TicketDAO().Supprimer(Idticket);
           // sa.stades = new stadeDAO().select();
                        
        }
      
        tableafficherticket.setModel(new TicketAdapter());// TODO add your handling code here:

        
        
        
        
        
    }//GEN-LAST:event_supprimerticketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererticketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererticketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouterticket;
    private javax.swing.JButton dcnx;
    private javax.swing.JLabel idticket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel meyelmatch;
    private javax.swing.JButton modifierticket;
    private javax.swing.JSpinner nbr_ticket;
    private javax.swing.JSpinner prixticket;
    private javax.swing.JTextField rechercherticket;
    private javax.swing.JButton supprimerticket;
    private javax.swing.JTable tableafficherticket;
    private javax.swing.JComboBox<String> ticket_joueurs;
    // End of variables declaration//GEN-END:variables
}
