/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;

import com.esprit.TFTpro.adpaters.StadeAdapter;
import com.esprit.TFTpro.adpaters.StadeAdapter2;
import com.esprit.TFTpro.dao.classes.stadeDAO;
import com.esprit.TFTpro.entities.stade;
import com.esprit.hellopi.dao.interfaces.IstadeDAO;
import com.esprit.technique.DataSource;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import com.lowagie.text.BadElementException;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.text.Document;

/**
 *
 * @author Taha
 */
public class gererStadeFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form gererStadeFrame2
     */
    
    List<stade>stades = new ArrayList<>();
    public List<stade> getList() {
        return stades;
    }
    stadeDAO DAO = new stadeDAO();
    public gererStadeFrame2() {
        stades=DAO.select();
        initComponents();
    }
   public String genCode(String email)
    {
        
        meyel.setText(email);
        return email;
        
        
    }
   String filename;
   byte[] img=null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfStadeNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfStadeCapacite = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfStadeTypeDeTerrain = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfStadeSurface = new javax.swing.JTextField();
        BStade = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BSupStade = new javax.swing.JButton();
        BModifStade = new javax.swing.JButton();
        BrechStade = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lStadeId = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        dcnx = new javax.swing.JButton();
        meyel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ajoutImage = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        imm = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new StadeAdapter());
        jTable2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable2MouseDragged(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Nom");

        tfStadeNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStadeNomActionPerformed(evt);
            }
        });

        jLabel2.setText("Capacite");

        jLabel3.setText("Type de Terrain");

        jLabel4.setText("Surface");

        tfStadeSurface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStadeSurfaceActionPerformed(evt);
            }
        });

        BStade.setText("Ajouter Stade");
        BStade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStadeActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(240, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel5.setText("      Gestion des Stades");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));

        BSupStade.setText("Supprimer");
        BSupStade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSupStadeActionPerformed(evt);
            }
        });

        BModifStade.setText("Modifier");
        BModifStade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifStadeActionPerformed(evt);
            }
        });

        BrechStade.setText("rechercher");
        BrechStade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrechStadeActionPerformed(evt);
            }
        });

        jButton2.setText("exporter PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        a.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                aPropertyChange(evt);
            }
        });
        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aKeyReleased(evt);
            }
        });

        dcnx.setText("Se déconnecter");
        dcnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcnxActionPerformed(evt);
            }
        });

        meyel.setText("jLabel2");

        jLabel6.setText("Welcome ");

        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ajoutImage.setText("ajout Image");
        ajoutImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutImageActionPerformed(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jLabel8.setText("selectionner un stade (appuyer puis deplacer curseur)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(imm, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lStadeId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfStadeNom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfStadeCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfStadeTypeDeTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfStadeSurface, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(BStade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BSupStade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BModifStade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrechStade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ajoutImage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(0, 290, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(dcnx))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(meyel)))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(meyel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcnx)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lStadeId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfStadeNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStadeCapacite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfStadeTypeDeTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfStadeSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BStade)
                            .addComponent(BModifStade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajoutImage)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BSupStade)
                            .addComponent(BrechStade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imm, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfStadeNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStadeNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStadeNomActionPerformed

    private void BStadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStadeActionPerformed
        DataSource.getInstance();
        IstadeDAO dao=new stadeDAO() {};
        stade stade= new stade();
        stade.setNom(tfStadeNom.getText());
        stade.setCapacite(Integer.parseInt(tfStadeCapacite.getText()));
        stade.setTypeDeTerrain(tfStadeTypeDeTerrain.getText());
        stade.setSurface(Integer.parseInt(tfStadeSurface.getText()));
        stade.setImage(img);
        

        dao.add(stade);
        jTable2.setModel(new StadeAdapter());
        // TOsDO add your handling code here:
    }//GEN-LAST:event_BStadeActionPerformed

    
    
    private void BSupStadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSupStadeActionPerformed
       
       StadeAdapter sa = new StadeAdapter();
        int x = jTable2.getSelectedRow();
        
        if(x == -1){
            
        JOptionPane.showMessageDialog(null, "\"Veuillez sélectioné une session !\"");
            
        }else{
            int id = Integer.parseInt(sa.getValueAt(x,0).toString());
            System.out.println(id);
            new stadeDAO().Supprimer(id);
           // sa.stades = new stadeDAO().select();
            
                        
            JOptionPane.showMessageDialog(null, "Selectionnez le Compte à supprimer");
        }
      
        jTable2.setModel(new StadeAdapter());// TODO add your handling code here:
    }//GEN-LAST:event_BSupStadeActionPerformed

    private void BModifStadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifStadeActionPerformed
 StadeAdapter sa = new StadeAdapter();
  int x = jTable2.getSelectedRow();

  int id = Integer.parseInt(sa.getValueAt(x, 0).toString());

  IstadeDAO dao = new stadeDAO();
        stade stade = new stade();
        stade.setId(Integer.parseInt(lStadeId.getText()));
        stade.setNom(tfStadeNom.getText());
        stade.setCapacite(Integer.parseInt(tfStadeCapacite.getText()));
        stade.setTypeDeTerrain(tfStadeTypeDeTerrain.getText());
        stade.setSurface(Integer.parseInt(tfStadeSurface.getText()));

       dao.Update(stade);
        jTable2.setModel(new StadeAdapter());
        JOptionPane.showMessageDialog(null, "Votre stade a ete modifier", "", JOptionPane.WARNING_MESSAGE);
        jTable2.setModel(new StadeAdapter());// TODO add your handling code here:
        
    }//GEN-LAST:event_BModifStadeActionPerformed

    private void BrechStadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrechStadeActionPerformed
        IstadeDAO dao = new stadeDAO();
        stade stade ;

        

//= new Idee();
       String s=a.getText();

        int k = (int)Integer.parseInt(s);
        stade = dao.Rechercher(s);

        
        tfStadeNom.setText(stade.getNom()+"");
        tfStadeCapacite.setText(stade.getCapacite()+"");
        tfStadeTypeDeTerrain.setText(stade.getTypeDeTerrain()+"");
        tfStadeSurface.setText(stade.getSurface()+"");
        jTable2.setModel(new StadeAdapter());
        /* ii.setIdIdee(idee.getIdIdee());

        modifTitre.setText(idee.getTitre()StadeAdapter2);
        modifDesc.setText(idee.getDescription());
        modifType.setText(idee.getType());   // TODO add your handling code here:*/
    }//GEN-LAST:event_BrechStadeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfStadeSurfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStadeSurfaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStadeSurfaceActionPerformed

    private void jTable2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseDragged

    StadeAdapter sa = new StadeAdapter();
  IstadeDAO dao = new stadeDAO();
        stade stade = new stade();
        int x = jTable2.getSelectedRow();
        
        if(x == -1){
            
       
            
        }else{
            int id = Integer.parseInt(sa.getValueAt(x, 0).toString());
            System.out.println(id);
            //String s = "1";
            //id = (int)Integer.parseInt(s);
             stade = dao.Rechercher(id);

         lStadeId.setText(stade.getId()+"");
        tfStadeNom.setText(stade.getNom()+"");
        tfStadeCapacite.setText(stade.getCapacite()+"");
        tfStadeTypeDeTerrain.setText(stade.getTypeDeTerrain()+"");
        tfStadeSurface.setText(stade.getSurface()+"");
            
                        
         
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseDragged

    private void aKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyReleased

    
     
    // TODO add your handling code here:
    }//GEN-LAST:event_aKeyReleased

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        StadeAdapter sa = new StadeAdapter();
        
        IstadeDAO dao = new stadeDAO();
        stade stade = new stade();
        String s=a.getText();

        
        jTable2.setModel(new StadeAdapter2(s));
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void aPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_aPropertyChange
        // TODO add your handling code here:
         StadeAdapter sa = new StadeAdapter();
        IstadeDAO dao = new stadeDAO();
        stade stade = new stade();
        String s=a.getText();

        
        jTable2.setModel(new StadeAdapter2(s));
    }//GEN-LAST:event_aPropertyChange

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyPressed

    private void dcnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcnxActionPerformed
        // TODO add your handling code here:
        Connect l =new  Connect();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_dcnxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Accueiladmin l =new  Accueiladmin();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ajoutImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutImageActionPerformed
JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        try{
        filename=f.getAbsolutePath();
        }catch(Exception e){
        filename = "";
        }
        jLabel7.setText(filename);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf= new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);

            }
            img = bos.toByteArray();
           
        }
        catch(Exception e){
            System.out.println("The URL was malformed ... ");

        }
                    filename = "";        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutImageActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    /*  byte[]image1=getList().get(jTable2.getSelectedRow()).getImage();
        BufferedImage imageee;
        try {
            imageee=ImageIO.read(new ByteArrayInputStream(image1));
            ImageIcon icon= new ImageIcon(imageee);
            imm.setIcon(icon);
           
        } catch (Exception ex) {
          ///  Logger.getLogger(jGererResto.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog( this, "Erreur se produit l'hors du chargement de l'image !"); 
        }  */
    }//GEN-LAST:event_jTable2MouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gererStadeFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gererStadeFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gererStadeFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gererStadeFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
   

                
                new gererStadeFrame2().setVisible(true);

            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModifStade;
    private javax.swing.JButton BStade;
    private javax.swing.JButton BSupStade;
    private javax.swing.JButton BrechStade;
    private javax.swing.JTextField a;
    private javax.swing.JButton ajoutImage;
    private javax.swing.JButton dcnx;
    private javax.swing.JLabel imm;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lStadeId;
    private javax.swing.JLabel meyel;
    private javax.swing.JTextField tfStadeCapacite;
    private javax.swing.JTextField tfStadeNom;
    private javax.swing.JTextField tfStadeSurface;
    private javax.swing.JTextField tfStadeTypeDeTerrain;
    // End of variables declaration//GEN-END:variables
}
