/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;

import com.esprit.TFTpro.adpaters.JeuJouerAdapter;
import com.esprit.TFTpro.entities.Matche;
import com.esprit.hellopi.gui.jeuResultatFrame2;
import com.esprit.technique.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.TableModel;

/**
 *
 * @author Taha
 */
public class jeuResultatFrame extends javax.swing.JFrame {
private Connection connection;
    /**

         
     * Creates new form jeuResultatFrame
     */
    public jeuResultatFrame() {
        initComponents();
        jTable1.setModel(new JeuJouerAdapter());
        connection= DataSource.getInstance().getConnection();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("voici vos paris");

        jTable1.setModel(new JeuJouerAdapter());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Accueiladmin l =new  Accueiladmin();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

 jeuResultatFrame2 j = new jeuResultatFrame2();
     int index = jTable1.getSelectedRow();
    TableModel table = jTable1.getModel();
    String id = table.getValueAt(index, 0).toString();
    String idjeu = table.getValueAt(index, 1).toString();
    String idutilisateur = table.getValueAt(index, 2).toString();
    String prix = table.getValueAt(index, 3).toString();
    String nbjoke = table.getValueAt(index, 4).toString();
    
    String choix1 = table.getValueAt(index, 5).toString();
    String choix2 = table.getValueAt(index, 6).toString();
    String choix3 = table.getValueAt(index, 7).toString();
    /*String match5 = table.getValueAt(index, 5).toString();
    String match6 = table.getValueAt(index, 6).toString();
    String match7 = table.getValueAt(index, 7).toString();
    String match8 = table.getValueAt(index, 8).toString();
    String match9 = table.getValueAt(index, 9).toString();
    String match10 = table.getValueAt(index, 10).toString();*/
 
    j.setVisible(true);
    j.lid.setText(id);
    j.lidjeu.setText(idjeu);
    j.lidutilisateur.setText(idutilisateur);
    j.lchoix1.setText(choix1);
    j.lchoix2.setText(choix2);
     j.lchoix3.setText(choix3);
      String requete = "SELECT resultat from matches where id=(select idmatch1_id from jeu where id=(select idjeu_id from pari where id="+id+"))";
          try {
            java.sql.Statement statement = connection
                    .createStatement();
            ResultSet resultat = statement.executeQuery(requete);
            while (resultat.next()) {
                Matche Matche = new Matche();
                Matche.setResultat(resultat.getString(1));
           String a;
            a = Matche.getResultat();
            
           // a = Matche.getResultat();
            System.out.println(a);
                j.lresultatchoix1.setText(a);  
            }
            
            
        } catch (SQLException ex) {
            System.out.println("erreur lors du chargement des stocks " + ex.getMessage());
            
        } 
          
              String requete2 = "SELECT resultat from matches where id=(select idmatch2_id from jeu where id=(select idjeu_id from pari where id="+id+"))";
          try {
            java.sql.Statement statement = connection
                    .createStatement();
            ResultSet resultat = statement.executeQuery(requete);
            while (resultat.next()) {
                Matche Matche = new Matche();
                Matche.setResultat(resultat.getString(1));
           String b;
            b = Matche.getResultat();
            
           // a = Matche.getResultat();
            System.out.println(b);
                j.lresultatchoix2.setText(b);  
            }
            
            
        } catch (SQLException ex) {
            System.out.println("erreur lors du chargement des stocks " + ex.getMessage());
            
        } 
          
                    String requete3 = "SELECT resultat from matches where id=(select idmatch3_id from jeu where id=(select idjeu_id from pari where id="+id+"))";
          try {
            java.sql.Statement statement = connection
                    .createStatement();
            ResultSet resultat = statement.executeQuery(requete);
            while (resultat.next()) {
                Matche Matche = new Matche();
                Matche.setResultat(resultat.getString(1));
           String c;
            c = Matche.getResultat();
            
           // a = Matche.getResultat();
            System.out.println(c);
                j.lresultatchoix3.setText(c);  
            }
            
            
        } catch (SQLException ex) {
            System.out.println("erreur lors du chargement des stocks " + ex.getMessage());
            
        } 
   /* j.Lmatch5.setText(match5);
    j.Lmatch6.setText(match6);
    j.Lmatch7.setText(match7);
    j.Lmatch8.setText(match8);
    j.Lmatch9.setText(match9);
    j.Lmatch10.setText(match10);*/        
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jeuResultatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jeuResultatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jeuResultatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jeuResultatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jeuResultatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
