/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;


import com.esprit.TFTpro.dao.classes.UtilisateurDAO;
import com.esprit.TFTpro.adpaters.ListeForumAdapter;

import com.esprit.hellopi.dao.interfaces.IUtilisateurDAO;
import com.esprit.TFTpro.entities.Utilisateur;
import com.esprit.technique.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hama
 */
public class LoginFrame extends javax.swing.JFrame {
       private Connection connection;
    /**
     * Creates new form LoginFrame
     */
           IUtilisateurDAO userDAO = new UtilisateurDAO();

    public LoginFrame() {
        initComponents();
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        pwd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Mot de passe");

        loginok.setText("connecter");
        loginok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginokActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/gui/tennis.jpg"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(loginok))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(loginok))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void loginokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginokActionPerformed

        // TODO add your handling code here:
                
        
               
String email=mail.getText();
String password=pwd.getText();



this.dispose();
connection= DataSource.getInstance().getConnection();        
Utilisateur Utilisateur = new Utilisateur();

        DataSource.getInstance();
        
            String query = "select login,password from Utilisateurs where username=? AND password=?";
        try {

            
            PreparedStatement ps= connection.prepareStatement(query);

ps.setString(1,mail.getText());
ps.setString(2,pwd.getText());
String maiil= mail.getText();

            ResultSet resultat = ps.executeQuery();
            
            
            
            if (resultat.next())
            {
              
            //Utilisateur.setIduser(resultat.getInt(1));
            Utilisateur.setLogin(resultat.getString(2));
            Utilisateur.setPassword(resultat.getString(3));
            //Utilisateur.setSolde(resultat.getInt(4));
                
                JOptionPane.showMessageDialog(null,"welcome" + " " + mail.getText());
             JframeForum f = new JframeForum();
             f.genCode(maiil);
             f.setVisible(true);
                  
              
             
             
                
            }
            else {
                JOptionPane.showMessageDialog(null,"invalid  username or password","access denied",JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(UtilisateurDAO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              /* 
          if(t1.getText().isEmpty() || t2.getText().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }
         else
            if(UtilisateurDAO.Authentification(t2.getText(), t2.getText())!=null)
            {
                System.out.println("sdsq");
                //       Session.Utilisateur = UtilisateurDAO.Authentification(t1.getText(), t2.getText());
             //   System.out.println(Session.Utilisateur.getSolde());
              
                if(Session.user.getRole() == 0)
                {
//                    System.out.println("vous etes un admin");
                    Home_admin h = new Home_admin();
                    setVisible(false);
                    getParent().add(h);
                    h.setVisible(true);

                    
                }
                else
                    if(Session.user.getRole()==1)
                    {
//                        System.out.println("****CLIENT");
                        Home_client h = new Home_client();
                        setVisible(false);
                        getParent().add(h);
                        h.setVisible(true);
                    }
                */
//                JOptionPane.showMessageDialog(null, "Bienvenue admin");
//                Home_admin h = new Home_admin();
//                setVisible(false);
//                getParent().add(h);
//                h.setVisible(true);
/*

      
               if(mail.getText().isEmpty() || pwd.getText().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }

        else
               {
        if( userDAO.authentification(mail.getText(), pwd.getText())!=null )
        {
            Session.Utilisateur = userDAO.authentification(mail.getText(), pwd.getText());
            System.out.println(Session.Utilisateur.getPwd());
            //                JOptionPane.showMessageDialog(null, "Bienvenue admin");
            //                Home_admin h = new Home_admin();
            //                setVisible(false);
            //                getParent().add(h);
            //                h.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Veuillez verifier vos informations dans le formulaire");
            mail.setText("");
            pwd.setText("");
        }
        
               }
*/
         
    }//GEN-LAST:event_loginokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginok;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField pwd;
    // End of variables declaration//GEN-END:variables
}
