/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.TFTpro.gui;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import com.esprit.TFTpro.dao.classes.UtilisateurDAO;
import com.esprit.TFTpro.entities.Utilisateur;
import javax.swing.JOptionPane;
/**
 *
 * @author Asma
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    exp.setVisible(false);
        expfi.setVisible(false);
        Grade.setVisible(false);
        Gradefi.setVisible(false);
        
        Cat.setVisible(false);
        catf.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fonction = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        AGE = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        CIN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        exp = new javax.swing.JLabel();
        expfi = new javax.swing.JSpinner();
        Cat = new javax.swing.JLabel();
        catf = new javax.swing.JComboBox();
        Gradefi = new javax.swing.JComboBox();
        ENVOYER = new javax.swing.JButton();
        Grade = new javax.swing.JLabel();
        CANCEL = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/TFTpro/gui/body.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel9.setText("Fonction:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 80, 80, 14);

        fonction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fan", "Arbitre", "Joueur", "Medecin", "Responsable" }));
        fonction.setAutoscrolls(true);
        fonction.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fonctionItemStateChanged(evt);
            }
        });
        fonction.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                fonctionCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fonctionInputMethodTextChanged(evt);
            }
        });
        fonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonctionActionPerformed(evt);
            }
        });
        getContentPane().add(fonction);
        fonction.setBounds(160, 70, 94, 30);

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 130, 90, 14);

        jLabel3.setText("Prenom:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 170, 80, 14);

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(160, 130, 94, 20);

        jLabel6.setText("E-mail:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 200, 70, 14);

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        getContentPane().add(prenom);
        prenom.setBounds(160, 160, 94, 20);

        jLabel4.setText("Age:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 230, 50, 14);

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        getContentPane().add(mail);
        mail.setBounds(160, 200, 94, 20);
        getContentPane().add(AGE);
        AGE.setBounds(160, 230, 94, 20);

        jLabel5.setText("CIN:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 280, 70, 14);
        getContentPane().add(CIN);
        CIN.setBounds(160, 270, 94, 20);

        jLabel7.setText("Login :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 440, 60, 14);

        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN);
        LOGIN.setBounds(160, 440, 94, 20);

        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(PASSWORD);
        PASSWORD.setBounds(160, 470, 94, 20);

        jLabel8.setText("Password :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 470, 70, 14);

        exp.setText("Experience :");
        getContentPane().add(exp);
        exp.setBounds(80, 330, 80, 14);
        getContentPane().add(expfi);
        expfi.setBounds(160, 320, 90, 20);

        Cat.setText("Categorie:");
        getContentPane().add(Cat);
        Cat.setBounds(80, 410, 70, 10);

        catf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Junior", "Senior", "Veterans" }));
        catf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catfActionPerformed(evt);
            }
        });
        getContentPane().add(catf);
        catf.setBounds(160, 400, 90, 20);

        Gradefi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "International", "National", "Amateur" }));
        Gradefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradefiActionPerformed(evt);
            }
        });
        getContentPane().add(Gradefi);
        Gradefi.setBounds(160, 360, 90, 20);

        ENVOYER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ENVOYER.setText("ENVOYER");
        ENVOYER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENVOYERActionPerformed(evt);
            }
        });
        getContentPane().add(ENVOYER);
        ENVOYER.setBounds(30, 510, 150, 23);

        Grade.setText("Grade :");
        getContentPane().add(Grade);
        Grade.setBounds(90, 360, 60, 20);

        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });
        getContentPane().add(CANCEL);
        CANCEL.setBounds(270, 510, 130, 23);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel10.setText("INSCRIPTION ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 10, 208, 33);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/TFTpro/gui/Adminbg.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 430, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fonctionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fonctionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fonctionItemStateChanged

    private void fonctionCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fonctionCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fonctionCaretPositionChanged

    private void fonctionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fonctionInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_fonctionInputMethodTextChanged

    private void fonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonctionActionPerformed
     
        System.out.println((String)fonction.getSelectedItem());
        if ("Arbitre".equals((String)fonction.getSelectedItem()))
        {

            Grade.setVisible(true);
            catf.setVisible(true);
        }
        else
        {exp.setVisible(false);
            expfi.setVisible(false);
            Grade.setVisible(false);
            catf.setVisible(false);
        }
        if ("Joueur".equals((String)fonction.getSelectedItem()))
        {
            Cat.setVisible(true);
            catf.setVisible(true);
            Grade.setVisible(true);
            Gradefi.setVisible(true);
        }
        else
        {
            Cat.setVisible(false);
            catf.setVisible(false);
            Grade.setVisible(false);
            Gradefi.setVisible(false);
        }
        if (("Medecin".equals((String)fonction.getSelectedItem()))|("Responsable".equals((String)fonction.getSelectedItem())))
        {
            exp.setVisible(true);
            expfi.setVisible(true);

        }
        else
        {
            exp.setVisible(false);
            expfi.setVisible(false);
        }
        if ("Arbitre".equals((String)fonction.getSelectedItem()))
        {
            exp.setVisible(true);
            expfi.setVisible(true);
            catf.setVisible(true);
            Cat.setVisible(true);
        }

    }//GEN-LAST:event_fonctionActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void catfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catfActionPerformed

    private void GradefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradefiActionPerformed

    private void ENVOYERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENVOYERActionPerformed
        if("Fan".equals((String)fonction.getSelectedItem()))
        {
            Utilisateur user = new Utilisateur();
            user.setNom(nom.getText());
            user.setPrenom(prenom.getText());
           
            user.setCIN(Integer.parseInt(CIN.getText()));
            user.setFonction((String) fonction.getSelectedItem());
            user.setLogin(LOGIN.getText());
            user.setPassword(PASSWORD.getText());
            user.setAutorisation("En cours");
            user.setEmail(mail.getText());
            String  fan="a:1:{i:0;s:12:ROLE_Fan;}";
            user.setRole(fan);
            UtilisateurDAO userdao = new UtilisateurDAO();
            userdao.ajout(user);
            
            JOptionPane.showMessageDialog(null, "Votre compte a été crée avec succées ", "", JOptionPane.OK_OPTION);

          
        }
        if("Arbitre".equals((String)fonction.getSelectedItem()))
        {
            Utilisateur user = new Utilisateur();
            user.setNom(nom.getText());
            user.setPrenom(prenom.getText());
            user.setAge((Integer) AGE.getValue());
            user.setCIN(Integer.parseInt(CIN.getText()));
            user.setExp((Integer) expfi.getValue());
            user.setCat((String) catf.getSelectedItem());
            user.setFonction((String) fonction.getSelectedItem());
            user.setLogin(LOGIN.getText());
            user.setPassword(PASSWORD.getText());
            user.setAutorisation("En attente");
            user.setEmail(mail.getText());
             String arbitre="a:1:{i:0;s:12:\"ROLE_ARBITRE\";}";
             user.setRole(arbitre);
            UtilisateurDAO userdao = new UtilisateurDAO();
            userdao.ajoutarbitre(user);
           
                      JOptionPane.showMessageDialog(null, "Votre compte a été crée avec succées", "", JOptionPane.OK_OPTION);

   
        }
        if("Joueur".equals((String)fonction.getSelectedItem()))
        {
            Utilisateur user = new Utilisateur();
            user.setNom(nom.getText());
            user.setPrenom(prenom.getText());
            user.setAge((Integer) AGE.getValue());
            user.setCIN(Integer.parseInt(CIN.getText()));
            user.setGrade((String) Gradefi.getSelectedItem());
            user.setCat((String) catf.getSelectedItem());
            user.setFonction((String) fonction.getSelectedItem());
            user.setLogin(LOGIN.getText());
            user.setPassword(PASSWORD.getText());
           
            user.setAutorisation("En cours");
            user.setEmail(mail.getText());
            String joueur="a:1:{i:0;s:12:\"ROLE_Joueur\";}";
user.setRole(joueur);
            UtilisateurDAO userdao = new UtilisateurDAO();
            userdao.ajoutjoueur(user);
                     JOptionPane.showMessageDialog(null, "Votre compte a été crée avec succées", "", JOptionPane.OK_OPTION);

   
            this.hide();
        }
        if(("Responsable".equals((String)fonction.getSelectedItem())))
        {
            Utilisateur user = new Utilisateur();
            user.setNom(nom.getText());
            user.setPrenom(prenom.getText());
            user.setAge((Integer) AGE.getValue());
            user.setCIN(Integer.parseInt(CIN.getText()));
            user.setExp((Integer) expfi.getValue());
            user.setFonction((String) fonction.getSelectedItem());
            user.setLogin(LOGIN.getText());
            user.setPassword(PASSWORD.getText());
            user.setAutorisation("En attente");
            user.setEmail(mail.getText());
String responsable="a:1:{i:0;s:12:\"ROLE_RESPONSABLE\";}";
user.setRole(responsable);
            UtilisateurDAO userdao = new UtilisateurDAO();

            userdao.ajoutmedecin(user);
                     JOptionPane.showMessageDialog(null, "Votre compte a été crée avec succées", "", JOptionPane.OK_OPTION);

   
            this.hide();
        }if(("Medecin".equals((String)fonction.getSelectedItem())))
         {
            Utilisateur user = new Utilisateur();
            user.setNom(nom.getText());
            user.setPrenom(prenom.getText());
            user.setAge((Integer) AGE.getValue());
            user.setCIN(Integer.parseInt(CIN.getText()));
            user.setExp((Integer) expfi.getValue());
            user.setFonction((String) fonction.getSelectedItem());
            user.setLogin(LOGIN.getText());
            user.setPassword(PASSWORD.getText());
            user.setAutorisation("En attente");
            user.setEmail(mail.getText());
String medecin="a:1:{i:0;s:12:\"ROLE_MEDECIN\";}";
user.setRole(medecin);
            UtilisateurDAO userdao = new UtilisateurDAO();

            userdao.ajoutmedecin(user);
                     JOptionPane.showMessageDialog(null, "Votre compte a été crée avec succées", "", JOptionPane.OK_OPTION);

   
            this.hide();
        }
    }//GEN-LAST:event_ENVOYERActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
      
        this.hide();
    }//GEN-LAST:event_CANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AGE;
    private javax.swing.JButton CANCEL;
    private javax.swing.JTextField CIN;
    private javax.swing.JLabel Cat;
    private javax.swing.JButton ENVOYER;
    private javax.swing.JLabel Grade;
    private javax.swing.JComboBox Gradefi;
    private javax.swing.JTextField LOGIN;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JComboBox catf;
    private javax.swing.JLabel exp;
    private javax.swing.JSpinner expfi;
    private javax.swing.JComboBox fonction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
